on:
  workflow_dispatch:
  schedule:
    # 每4小时运行一次
    - cron: '20 */4 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - name: Install and Import Module to convert yaml
        shell: PowerShell
        run: |
          Install-Module "powershell-yaml" -Force
          Import-Module "powershell-yaml"
      - uses: actions/checkout@main
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: '1'
