name: Excavator
on:
  workflow_dispatch:
  schedule:
    # At minute 20 past every 4th hour.
    - cron: '20 */4 * * *'
  workflow_run:
    workflows: [Update README]
    types: [completed]
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install and Import Module to convert yaml
        shell: PowerShell
        run: |
          Install-Module "powershell-yaml" -Force
          Import-Module "powershell-yaml"

      - name: Install Selenium
        run: |
          pip install selenium

      - uses: actions/checkout@v4

      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: "1"
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: abgox/gh-workflow-keepalive@main
