name: Excavator
on:
  workflow_dispatch:
  schedule:
    # 每4小时运行一次
    - cron: "20 */4 * * *"
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install and Import Module to convert yaml
        shell: PowerShell
        run: |
          Install-Module "powershell-yaml" -Force
          Import-Module "powershell-yaml"

      - uses: actions/checkout@main

      - name: Install Selenium
        run: |
          pip install selenium

      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: "1"
